version: "3"
services:
  myapp:
    image: apache/tika:1.24.1
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    ports:
    - target: 9998
      published: __PORT__
