#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE 
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

# This should be a symetric version of what happens in the install script

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status $app >/dev/null
then
	ynh_script_progression --message="Removing $app service integration..." --weight=1
	yunohost service remove $app
fi

ynh_remove_systemd_config

ynh_remove_nginx_config

ynh_remove_logrotate

# Remove other various files specific to the app... such as :

ynh_secure_remove --file="/var/log/$app"

# Remove conf that put MySQL (MariaDB) accessible from all IP
ynh_secure_remove --file="/etc/mysql/mariadb.conf.d/90-$app.cnf"
systemctl restart mariadb.service
# Firewall should NOT allow Docker containers internal IP to reach MySQL
# Should be the OPPOSITE as ../hooks/post_iptable_rules
iptables -D INPUT -s 10.0.0.0/8 -p tcp -m tcp --dport 3306 -j ACCEPT
iptables -D INPUT -s 192.168.0.0/16 -p tcp -m tcp --dport 3306 -j ACCEPT
iptables -D INPUT -s 172.16.0.0/12 -p tcp -m tcp --dport 3306 -j ACCEPT
# MySQL user should be allowed to connect only from localhost
ynh_mysql_execute_as_root --sql="RENAME USER '$db_user'@'%' TO '$db_user'@'localhost'"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
